(function(){/*


 mea3D - HTML5 3D Engine - http://mea3d.googlecode.com

 Author:  Mustafa Emre Acer
 Version: 1.0.2
*/
if("undefined"==typeof window.mea3D)var mea3D={};mea3D.Renderer2D=function(a){if(a)this.canvas=a,this.width=parseInt(this.canvas.width,10),this.height=parseInt(this.canvas.height,10),this.pixelSize=1,this.context=this.canvas.getContext("2d"),this.imageData=this.context.createImageData(this.width*this.pixelSize,this.height*this.pixelSize)};
mea3D.Renderer2D.prototype={setPixel:function(a,b,c){a=this.width*b+a<<2;this.imageData.data[a]=c.r;this.imageData.data[a+1]=c.g;this.imageData.data[a+2]=c.b;this.imageData.data[a+3]=255},beginPath:function(){},closePath:function(){},moveTo:function(){},lineTo:function(){},fill:function(){},stroke:function(){},fillText:function(){},fillRect:function(a,b,c,d){a=new mea3D.ColorRGBA(255,255,0);d=b+d;for(c=b;c<d;++c)for(var e=b;e<d;++e)this.setPixel(e,c,a)},arc:function(){},draw:function(){this.context.putImageData(this.imageData,
0,0);this.setPixel(100,100,new mea3D.ColorRGBA(255,0,0))}};mea3D.getOptions=function(a,b){var c={};if(b)for(var d in b)c[d]=a&&d in a?a[d]:b[d];return c};
mea3D.Utils={getPageOffsetTop:function(a){return a.offsetTop+(a.offsetParent?mea3D.Utils.getPageOffsetTop(a.offsetParent):0)},getPageOffsetLeft:function(a){return a.offsetLeft+(a.offsetParent?mea3D.Utils.getPageOffsetLeft(a.offsetParent):0)},getXYValues:function(a){if(!a)return{x:-1,y:-1};var b=a.split("x"),a=parseInt(b[0],10),b=parseInt(b[1],10);return{x:a,y:b}},getElementsByTagName:function(a,b){for(var b=b.toUpperCase(),c=a.firstChild,d=[];c;)c.tagName==b&&d.push(c);return d},getCanvasElement:function(a){if(!a)return null;
var b=null;return b=a.getElementsByTagName?a.getElementsByTagName("canvas")&&a.getElementsByTagName("canvas")[0]:mea3D.Utils.getElementsByTagName("canvas")&&mea3D.Utils.getElementsByTagName("canvas")[0]},createCanvas:function(a,b,c){var d=document.createElement("canvas");d.width=b;d.height=c;a.appendChild(d);return d}};mea3D.LogLevel={LOG_ALL:0,LOG_DEBUG:1,LOG_INFO:2,LOG_ERROR:3,LOG_NONE:4};
mea3D.Logging={log:function(a){"undefined"!=typeof window.console&&window.console.log(a);var b=document.getElementById("debugDiv");if(b){if(2E4<b.innerHTML.length)b.innerHTML="";b.innerHTML+=a.replace(/\n/g,"<br>")+"<br>";document.getElementById("debugDivScrollTo")&&document.getElementById("debugDivScrollTo").scrollIntoView()}},logByLevel:function(a,b){var c=document.getElementById("loggingLevel")?document.getElementById("loggingLevel").selectedIndex:0;if(b){if(b<c)return}else if(mea3D.LogLevel.LOG_DEBUG<
c)return;mea3D.Logging.log(a)},debug:function(a){mea3D.Logging.logByLevel(a,mea3D.LogLevel.LOG_DEBUG)},info:function(a){mea3D.Logging.logByLevel(a,mea3D.LogLevel.LOG_INFO)},error:function(a){mea3D.Logging.logByLevel(a,mea3D.LogLevel.LOG_ERROR)}};mea3D.ColorRGBA=function(a,b,c,d){this.r=a;this.g=b;this.b=c;this.a="undefined"==typeof d?1:d};mea3D.ColorRGBA.createFromValues=function(a){return new mea3D.ColorRGBA(a[0],a[1],a[2],a[3])};
mea3D.ColorRGBA.prototype={toString:function(){return"rgb("+Math.floor(255*this.r)+","+Math.floor(255*this.g)+","+Math.floor(255*this.b)+")"},equals:function(a){return this.r==a.r&&this.g==a.g&&this.b==a.b},copy:function(){return new mea3D.ColorRGBA(this.r,this.g,this.b,this.a)},scale:function(a,b,c){return new mea3D.ColorRGBA(this.r*a,this.g*b,this.b*c)},addColor:function(a){return new mea3D.ColorRGBA(this.r+a.r,this.g+a.g,this.b+a.b,this.a+a.a)},add:function(a,b,c,d){return new mea3D.ColorRGBA(this.r+
a,this.g+b,this.b+c,this.a+d)},divide:function(a){return 0==a?null:new mea3D.ColorRGBA(this.r/a,this.g/a,this.b/a,this.a/a)}};mea3D.Vector2=function(a,b){this.x=a?a:0;this.y=b?b:0};mea3D.Vector2.prototype={toString:function(){return"("+this.x.toFixed(3)+","+this.y.toFixed(3)+")"},scale:function(a){return new mea3D.Vector2(this.x*a,this.y*a)},add:function(a){return new mea3D.Vector2(this.x+a.x,this.y+a.y)},subt:function(a){return new mea3D.Vector2(this.x-a.x,this.y-a.y)},dot:function(a){return this.x*a.x+this.y*a.y},mag:function(){return Math.sqrt(this.x*this.x+this.y*this.y)}};
mea3D.Vector3=function(a,b,c,d){this.x=a?a:0;this.y=b?b:0;this.z=c?c:0;this.w=d?d:1};
mea3D.Vector3.prototype={toString:function(){return"("+this.x.toFixed(3)+","+this.y.toFixed(3)+","+this.z.toFixed(3)+",w:"+this.w.toFixed(3)+")"},equals:function(a){return 1.0E-4<Math.abs(this.x-a.x)||1.0E-4<Math.abs(this.y-a.y)||1.0E-4<Math.abs(this.z-a.z)||1.0E-4<Math.abs(this.w-a.w)?!1:!0},copy:function(){return new mea3D.Vector3(this.x,this.y,this.z,this.w)},scale:function(a){return new mea3D.Vector3(this.x*a,this.y*a,this.z*a)},scale3:function(a,b,c){return new mea3D.Vector3(this.x*a,this.y*
b,this.z*c)},add:function(a){return new mea3D.Vector3(this.x+a.x,this.y+a.y,this.z+a.z)},subt:function(a){return new mea3D.Vector3(this.x-a.x,this.y-a.y,this.z-a.z)},mag:function(){return Math.sqrt(this.x*this.x+this.y*this.y+this.z*this.z)},mag2:function(){return this.x*this.x+this.y*this.y+this.z*this.z},norm:function(){return this.scale(1/this.mag())},dot:function(a){return this.x*a.x+this.y*a.y+this.z*a.z},cross:function(a){return new mea3D.Vector3(this.y*a.z-this.z*a.y,this.z*a.x-this.x*a.z,
this.x*a.y-this.y*a.x)},set:function(a,b,c){this.x=a;this.y=b;this.z=c}};mea3D.Line3=function(a,b){this.v1=a;this.v2=b};mea3D.Line3.prototype={toString:function(){return this.v1.toString()+","+this.v2.toString()},length:function(){var a=this.v1.x-this.v2.x,b=this.v1.y-this.v2.y,c=this.v1.z-this.v2.z;return Math.sqrt(a*a+b*b+c*c)},direction:function(){return this.v2.subt(this.v1).norm()}};mea3D.Matrix4=function(a){this.vals=a?a:[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]};
mea3D.Matrix4.prototype={toString:function(){for(var a="\n",b=0;4>b;b++){for(var a=a+"[",c=0;4>c;c++)a=a+this.vals[b][c].toFixed(3)+", ";a+="]\n"}return a},equals:function(a){for(var b=0;4>b;b++)for(var c=0;4>c;c++)if(1.0E-4<Math.abs(this.vals[c][b]-a.vals[c][b]))return!1;return!0},loadIdentity:function(){this.vals=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]},scale:function(a){for(var b=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],c=0;4>c;c++)for(var d=0;4>d;d++)b[c][d]=a*this.vals[c][d];return new mea3D.Matrix4(b)},
mult:function(a){for(var b=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],c=0;4>c;c++)for(var d=0;4>d;d++)for(var e=0;4>e;e++)b[c][d]+=this.vals[c][e]*a.vals[e][d];return new mea3D.Matrix4(b)},multVector3:function(a){var b=new mea3D.Vector3(0,0,0);b.x=this.vals[0][0]*a.x+this.vals[0][1]*a.y+this.vals[0][2]*a.z+this.vals[0][3]*a.w;b.y=this.vals[1][0]*a.x+this.vals[1][1]*a.y+this.vals[1][2]*a.z+this.vals[1][3]*a.w;b.z=this.vals[2][0]*a.x+this.vals[2][1]*a.y+this.vals[2][2]*a.z+this.vals[2][3]*a.w;b.w=this.vals[3][0]*
a.x+this.vals[3][1]*a.y+this.vals[3][2]*a.z+this.vals[3][3]*a.w;return b},add:function(a){for(var b=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],c=0;4>c;c++)for(var d=0;4>d;d++)b[c][d]=this.vals[c][d]+a.vals[c][d];return new mea3D.Matrix4(b)},subt:function(a){return this.add(a.scale(-1))},transpose:function(){for(var a=new mea3D.Matrix4,b=0;4>b;b++)for(var c=0;4>c;c++)a.vals[c][b]=this.vals[b][c];return a},normalize:function(){var a=this.vals[3][3];if(0==a)return mea3D.Logging.log("ERROR: w==0 in Matrix"),
null;for(var b=new mea3D.Matrix4,c=0;4>c;c++)for(var d=0;4>d;d++)b.vals[d][c]=this.vals[c][d]/a;return b},transformVector:function(a){var b=new mea3D.Vector3(0,0,0);b.x=a.x*this.vals[0][0]+a.y*this.vals[1][0]+a.z*this.vals[2][0]+this.vals[3][0];b.y=a.x*this.vals[0][1]+a.y*this.vals[1][1]+a.z*this.vals[2][1]+this.vals[3][1];b.z=a.x*this.vals[0][2]+a.y*this.vals[1][2]+a.z*this.vals[2][2]+this.vals[3][2];b.w=a.x*this.vals[0][3]+a.y*this.vals[1][3]+a.z*this.vals[2][3]+this.vals[3][3];return b},toArray:function(){return this.vals[0].concat(this.vals[1]).concat(this.vals[2]).concat(this.vals[3])}};mea3D.Transformation=function(a,b,c){this.position=a?a:new mea3D.Vector3(0,0,0);this.rotation=c?c:new mea3D.Vector3(0,0,0);this.scaling=b?b:new mea3D.Vector3(1,1,1);this.update()};
mea3D.Transformation.prototype={toString:function(){return"position: "+this.position.toString()+"rotation: "+this.rotation.toString()+"scaling : "+this.scaling.toString()},copy:function(){var a=new mea3D.Transformation(this.position.copy(),this.scaling.copy(),this.rotation.copy());a.update();return a},update:function(){this.scaleMatrix=mea3D.Math.getScaleMatrix4(this.scaling.x,this.scaling.y,this.scaling.z);this.rotationMatrix=mea3D.Math.getRotationMatrix4(this.rotation.x,this.rotation.y,this.rotation.z);
this.translationMatrix=mea3D.Math.getTranslationMatrix4(this.position.x,this.position.y,this.position.z);this.matrix=mea3D.Math.getTransformationMatrix4(this.scaling,this.rotation,this.position)},combine:function(a){var b=new mea3D.Transformation;b.position=this.position.add(a.position);b.rotation=this.rotation.copy();b.scaling.x=this.scaling.x*a.scaling.x;b.scaling.y=this.scaling.y*a.scaling.y;b.scaling.z=this.scaling.z*a.scaling.z;b.update();return b},moveTo:function(a,b,c){this.position.x=a;this.position.y=
b;this.position.z=c;this.update()},move:function(a,b,c){this.position.x+=a;this.position.y+=b;this.position.z+=c;this.update()},rotate:function(a,b,c){this.rotation.x+=a;this.rotation.y+=b;this.rotation.z+=c;this.update()},scale:function(a){this.scaling.x=a;this.scaling.y=a;this.scaling.z=a;this.update()},scale3:function(a,b,c){this.scaling.x=a;this.scaling.y=b;this.scaling.z=c;this.update()}};mea3D.Math={getScaleMatrix4:function(a,b,c){return new mea3D.Matrix4([[a,0,0,0],[0,b,0,0],[0,0,c,0],[0,0,0,1]])},getTranslationMatrix4:function(a,b,c){return new mea3D.Matrix4([[1,0,0,0],[0,1,0,0],[0,0,1,0],[a,b,c,1]])},getRotationMatrix4:function(a,b,c){a=mea3D.Math.getMatrixRotationX4(a);b=mea3D.Math.getMatrixRotationY4(b);c=mea3D.Math.getMatrixRotationZ4(c);return mea3D.Math.mult4(mea3D.Math.mult4(a,b),c)},getMatrixRotationX4:function(a){var b=Math.sin(a),a=Math.cos(a);return new mea3D.Matrix4([[1,
0,0,0],[0,a,b,0],[0,-b,a,0],[0,0,0,1]])},getMatrixRotationY4:function(a){var b=Math.sin(a),a=Math.cos(a);return new mea3D.Matrix4([[a,0,-b,0],[0,1,0,0],[b,0,a,0],[0,0,0,1]])},getMatrixRotationZ4:function(a){var b=Math.sin(a),a=Math.cos(a);return new mea3D.Matrix4([[a,b,0,0],[-b,a,0,0],[0,0,1,0],[0,0,0,1]])},mult4:function(a,b){var c=new mea3D.Matrix4;c.vals[0][0]=a.vals[0][0]*b.vals[0][0]+a.vals[0][1]*b.vals[1][0]+a.vals[0][2]*b.vals[2][0]+a.vals[0][3]*b.vals[3][0];c.vals[0][1]=a.vals[0][0]*b.vals[0][1]+
a.vals[0][1]*b.vals[1][1]+a.vals[0][2]*b.vals[2][1]+a.vals[0][3]*b.vals[3][1];c.vals[0][2]=a.vals[0][0]*b.vals[0][2]+a.vals[0][1]*b.vals[1][2]+a.vals[0][2]*b.vals[2][2]+a.vals[0][3]*b.vals[3][2];c.vals[0][3]=a.vals[0][0]*b.vals[0][3]+a.vals[0][1]*b.vals[1][3]+a.vals[0][2]*b.vals[2][3]+a.vals[0][3]*b.vals[3][3];c.vals[1][0]=a.vals[1][0]*b.vals[0][0]+a.vals[1][1]*b.vals[1][0]+a.vals[1][2]*b.vals[2][0]+a.vals[1][3]*b.vals[3][0];c.vals[1][1]=a.vals[1][0]*b.vals[0][1]+a.vals[1][1]*b.vals[1][1]+a.vals[1][2]*
b.vals[2][1]+a.vals[1][3]*b.vals[3][1];c.vals[1][2]=a.vals[1][0]*b.vals[0][2]+a.vals[1][1]*b.vals[1][2]+a.vals[1][2]*b.vals[2][2]+a.vals[1][3]*b.vals[3][2];c.vals[1][3]=a.vals[1][0]*b.vals[0][3]+a.vals[1][1]*b.vals[1][3]+a.vals[1][2]*b.vals[2][3]+a.vals[1][3]*b.vals[3][3];c.vals[2][0]=a.vals[2][0]*b.vals[0][0]+a.vals[2][1]*b.vals[1][0]+a.vals[2][2]*b.vals[2][0]+a.vals[2][3]*b.vals[3][0];c.vals[2][1]=a.vals[2][0]*b.vals[0][1]+a.vals[2][1]*b.vals[1][1]+a.vals[2][2]*b.vals[2][1]+a.vals[2][3]*b.vals[3][1];
c.vals[2][2]=a.vals[2][0]*b.vals[0][2]+a.vals[2][1]*b.vals[1][2]+a.vals[2][2]*b.vals[2][2]+a.vals[2][3]*b.vals[3][2];c.vals[2][3]=a.vals[2][0]*b.vals[0][3]+a.vals[2][1]*b.vals[1][3]+a.vals[2][2]*b.vals[2][3]+a.vals[2][3]*b.vals[3][3];c.vals[3][0]=a.vals[3][0]*b.vals[0][0]+a.vals[3][1]*b.vals[1][0]+a.vals[3][2]*b.vals[2][0]+a.vals[3][3]*b.vals[3][0];c.vals[3][1]=a.vals[3][0]*b.vals[0][1]+a.vals[3][1]*b.vals[1][1]+a.vals[3][2]*b.vals[2][1]+a.vals[3][3]*b.vals[3][1];c.vals[3][2]=a.vals[3][0]*b.vals[0][2]+
a.vals[3][1]*b.vals[1][2]+a.vals[3][2]*b.vals[2][2]+a.vals[3][3]*b.vals[3][2];c.vals[3][3]=a.vals[3][0]*b.vals[0][3]+a.vals[3][1]*b.vals[1][3]+a.vals[3][2]*b.vals[2][3]+a.vals[3][3]*b.vals[3][3];return c},getProjectionMatrix4:function(a,b,c,d){var c=1/Math.tan(0.5*c),d=1/Math.tan(0.5*d),b=b/(b-a),e=new mea3D.Matrix4;e.vals[0][0]=c;e.vals[1][1]=d;e.vals[2][2]=b;e.vals[2][3]=1;e.vals[3][2]=-b*a;return e},getCameraMatrix4:function(a,b,c){var b=b.subt(a).norm(),c=c.cross(b).norm(),d=b.cross(c),e=-c.dot(a),
f=-d.dot(a),a=-b.dot(a);return new mea3D.Matrix4([[c.x,d.x,b.x,0],[c.y,d.y,b.y,0],[c.z,d.z,b.z,0],[e,f,a,1]])},getScreenProjectionMatrix4:function(a,b,c,d,e,f){return new mea3D.Matrix4([[0.5*c,0,0,0],[0,0.5*-d,0,0],[0,0,f-e,0],[a+0.5*c,b+0.5*d,e,1]])},rotateVector3:function(a,b,c,d){b=mea3D.Math.getRotationMatrix4(b,c,d);return mea3D.Math.transformPoint(a,b)},transformPoint:function(a,b){return new mea3D.Vector3(b.vals[0][0]*a.x+b.vals[1][0]*a.y+b.vals[2][0]*a.z+b.vals[3][0],b.vals[0][1]*a.x+b.vals[1][1]*
a.y+b.vals[2][1]*a.z+b.vals[3][1],b.vals[0][2]*a.x+b.vals[1][2]*a.y+b.vals[2][2]*a.z+b.vals[3][2])},getFaceCenter:function(a,b,c,d){return d?new mea3D.Vector3((a.x+b.x+c.x+d.x)/4,(a.y+b.y+c.y+d.y)/4,(a.z+b.z+c.z+d.z)/4):new mea3D.Vector3((a.x+b.x+c.x)/3,(a.y+b.y+c.y)/3,(a.z+b.z+c.z)/3)},getFaceNormal:function(a,b,c){b=a.subt(b);return a.subt(c).cross(b).norm()},getTransformationMatrix4:function(a,b,c){a=mea3D.Math.getScaleMatrix4(a.x,a.y,a.z);b=mea3D.Math.getRotationMatrix4(b.x,b.y,b.z);c=mea3D.Math.getTranslationMatrix4(c.x,
c.y,c.z);a=mea3D.Math.mult4(b,a);return mea3D.Math.mult4(a,c)},mouseCoordsToDirectionVector:function(a,b){var c=1-(a*a+b*b),c=0<c?Math.sqrt(c):0;return(new mea3D.Vector3(a,-b,c)).norm()},getRotationMatrixFromOrientation:function(a){var b=new mea3D.Vector3(0,0,1),c=new mea3D.Vector3,c=a.z;-0.999999999<c&&0.999999999>c?(b=b.subt(a).scale(c).norm(),c=a.cross(b)):(b=new mea3D.Vector3(a.z,0,-a.x),c=new mea3D.Vector3(0,1,0));return(new mea3D.Matrix4([[b.x,b.y,b.z,0],[c.x,c.y,c.z,0],[a.x,a.y,a.z,0],[0,0,
0,1]])).transpose()},distanceSquaredPointToLine:function(a,b,c){var d=b.add(c),b=a.subt(b),a=a.subt(d);return b.cross(a).mag2()/c.mag2()},rotateVectorAroundAxis:function(a,b,c){var d=b.x,e=b.y,f=b.z,g=a.x,h=a.y,i=a.z,k=Math.sin(c),c=Math.cos(c),j=new mea3D.Vector3(0,0,0),a=a.dot(b),b=b.mag();j.x=d*a+(g*(e*e+f*f)-d*(e*h+f*i))*c+b*(-f*h+e*i)*k;j.y=e*a+(h*(d*d+f*f)-e*(d*g+f*i))*c+b*(f*g-d*i)*k;j.z=f*a+(i*(d*d+e*e)-f*(d*g+e*h))*c+b*(-e*g+d*h)*k;return j}};mea3D.Math.Util={getReflectedRay:function(a,b){var c=2*a.dot(b),c=a.scale(c);return b.subt(c)},catmullRomSplinePos:function(a,b,c,d,e){var f=e*e,g=f*e,h=b.scale(2),i=a.scale(2),k=b.scale(5),j=c.scale(4),b=b.scale(3),l=c.scale(3),c=c.subt(a).scale(e),f=i.subt(k).add(j).subt(d).scale(f),a=b.add(d).subt(a.add(l)).scale(g);return h.add(c).add(f).add(a).scale(0.5)},catmullRomSplineTangent:function(a,b,c,d,e){var f=e*e,g=a.scale(2),h=b.scale(5),i=c.scale(4),b=b.scale(3),k=c.scale(3),c=c.subt(a),e=g.subt(h).add(i).subt(d).scale(2*
e),a=b.add(d).subt(a.add(k)).scale(3*f);return c.add(e).add(a).scale(0.5)},getRayPolygonListIntersection:function(a,b,c,d){var e={polygonIndex:-1,distance:-1},f=a.length;"undefined"==typeof d&&(d=-1);var g=new mea3D.Vector3(0,0,0);new mea3D.Vector3(0,0,0);new mea3D.Vector3(0,0,0);for(var h,i,k,j,l=0;l<f;l++)if(l!=d&&(i=a[l],h=i.normal,k=i.minusCenterDotNormal,j=c.dot(h),!(0>=j)&&(h=-(k+h.dot(b))/j,!(0>=h)))){g.set(b.x+c.x*h,b.y+c.y*h,b.z+c.z*h);if(i.v4){if(j=mea3D.Math.getPointCoordsInsideTriangle(g,
i.v1.pos,i.v2.pos,i.v3.pos),k=j.s,j=j.t,0>k||0>j||1<k+j)if(j=mea3D.Math.getPointCoordsInsideTriangle(g,i.v3.pos,i.v4.pos,i.v1.pos),k=j.s,j=j.t,0>k||0>j||1<k+j)continue}else if(j=mea3D.Math.getPointCoordsInsideTriangle(g,i.v1.pos,i.v2.pos,i.v3.pos),k=j.s,j=j.t,0>k||0>j||1<k+j)continue;if(h<e.distance||-1==e.distance)e.distance=h,e.polygonIndex=l,e.polygon=i,e.coords={s:k,t:j},e.position=g}return 0<=e.polygonIndex?e:null},getPointCoordsInsideTriangle:function(a,b,c,d){var c=c.subt(b),d=d.subt(b),e=
a.subt(b),a=c.dot(d),b=e.dot(d),e=e.dot(c),c=c.dot(c),d=d.dot(d),f=a*a-c*d;return{s:(a*b-d*e)/f,t:(a*e-c*b)/f}},getPixelDirectionVector:function(a,b,c,d,e,f,g,h,i){i=a/2;b/=2;c=(c-i)/i;d=(d-b)/b;i=h.cross(g);e=mea3D.Math.rotateVectorAroundAxis(g,h,0.5*e*c);return e=mea3D.Math.rotateVectorAroundAxis(e,i,0.5*f*d)},getIlluminatingLights:function(a,b,c,d){for(var e=[],f=0;f<c.length;f++){var g=c[f],h;switch(g.type){case mea3D.LightType.POINT:h=g.position.subt(a).norm();break;case mea3D.LightType.DIRECTIONAL:h=
g.direction}h&&(mea3D.Math.Util.getRayPolygonListIntersection(b,a,h,d)||e.push(g))}return e},computeLighting:function(a,b,c,d,e){for(var f=new mea3D.ColorRGBA(0,0,0),g=0;g<d.length;g++)if(d[g].enabled){var h=d[g].calculateColor(c,a,b);h&&(f.r+=h.r,f.g+=h.g,f.b+=h.b)}c.enableAmbientColor&&c.ambientColor&&e&&(f.r+=c.ambientColor.r*e.r,f.g+=c.ambientColor.g*e.g,f.b+=c.ambientColor.b*e.b);c.enableEmitColor&&c.emitColor&&(f.r+=c.emitColor.r,f.g+=c.emitColor.g,f.b+=c.emitColor.b);return f},getBoundingSphere:function(a,
b,c,d){var e=c.subt(a),f=e.mag(),a=(f+(b+d))/2,b=(f+b-d)/2,c=c.add(e.norm().scale(-b));return{radius:a,position:c}},getMinimumBoundingSphere:function(a){if(!a||0==a.length)return null;for(var b=a[0].radius,c=a[0].position,d=1;d<a.length;d++)c=mea3D.Math.getBoundingSphere(c,b,a[d].position,a[d].radius),b=c.radius,c=c.position;return{radius:b,position:c}}};mea3D.Camera=function(a,b,c,d,e){this.lookAtPos=null;a&&b&&c?(this.eyePos=a,this.eyeDir=b.norm(),this.upVector=c,this.fovHorizontal=d,this.fovVertical=e,this.update()):this.reset()};
mea3D.Camera.prototype={toString:function(){return"mea3D.Camera:{eyePos:"+this.eyePos.toString()+", eyeDir:"+this.eyeDir.toString()+"}"},reset:function(){this.eyePos=new mea3D.Vector3(0,0,0);this.eyeDir=new mea3D.Vector3(0,0,1);this.upVector=new mea3D.Vector3(0,1,0);this.update()},update:function(){this.lookAtPos=this.eyePos.add(this.eyeDir.norm());this.leftVector=this.upVector.cross(this.eyeDir).norm();this.viewTransform=mea3D.Math.getCameraMatrix4(this.eyePos,this.lookAtPos,this.upVector)},lookAt:function(a){this.eyeDir=
a.subt(this.eyePos);this.upVector=this.leftVector.cross(this.eyeDir).norm();this.update()},moveForwardBackward:function(a){if(0!=a)this.eyePos=this.eyePos.add(this.eyeDir.norm().scale(a))},moveLeftRight:function(a){if(0!=a)this.eyePos=this.eyePos.add(this.upVector.cross(this.eyeDir).norm().scale(a))},rotateYaw:function(a){this.eyeDir=mea3D.Math.rotateVector3(this.eyeDir,0,a,0)},rotatePitch:function(a){this.eyeDir=mea3D.Math.rotateVector3(this.eyeDir,0,0,a)},moveUpDown:function(a){if(0!=a)this.eyePos=
this.eyePos.add(this.upVector.scale(a))},setEyePos:function(a){this.eyePos=new mea3D.Vector3(a.x,a.y,a.z)},getEyePos:function(){return this.eyePos},moveTo:function(a){this.eyePos=new mea3D.Vector3(a.x,a.y,a.z)},getEyeDir:function(){return this.eyeDir},setEyeDir:function(a){this.eyeDir=(new mea3D.Vector3(a.x,a.y,a.z)).norm()},getFovHorizontal:function(){return this.fovHorizontal},setFovHorizontal:function(a){this.fovHorizontal=a},getFovVertical:function(){return this.fovVertical},setFovVertical:function(a){this.fovVertical=
a},getUpVector:function(){return this.upVector},setUpVector:function(a){this.upVector=new mea3D.Vector3(a.x,a.y,a.z)},getViewTransform:function(){return this.viewTransform},getLeftVector:function(){return this.leftVector},moveByMouseDelta:function(a,b){this.eyeDir=mea3D.Math.rotateVectorAroundAxis(this.eyeDir,this.upVector,a).norm();var c=this.upVector.cross(this.eyeDir).norm();this.eyeDir=mea3D.Math.rotateVectorAroundAxis(this.eyeDir,c,b).norm();this.lookAtPos=this.eyePos.add(this.eyeDir)}};mea3D.ViewPort=function(a,b,c,d,e,f){this.x=a;this.y=b;this.width=c;this.height=d;this.zNear=e;this.zFar=f};mea3D.Vertex=function(a,b,c,d,e,f,g){this.pos=new mea3D.Vector3(0,0,0);this.pos.x=a;this.pos.y=b;this.pos.z=c;this.normal=new mea3D.Vector3(0,0,0);if(d)this.normal.x=d;if(e)this.normal.y=e;if(f)this.normal.z=f;this.color=g?g:"#fff"};mea3D.Vertex.fromVector=function(a){return new mea3D.Vertex(a.x,a.y,a.z)};mea3D.RenderableType={POLYGON:1,SURFACE:2,TEXT:3};
mea3D.Polygon=function(a,b,c,d,e,f,g,h){this.type=a;this.v1=b;this.v2=c;this.v3=d;this.vertexCount=(this.v4=e)?4:3;f?this.transformedVertices=f:(this.transformedVertices={},this.transformedVertices.v1=new mea3D.Vector3(0,0,0),this.transformedVertices.v2=new mea3D.Vector3(0,0,0),this.transformedVertices.v3=new mea3D.Vector3(0,0,0),this.transformedVertices.v4=new mea3D.Vector3(0,0,0));g?this.projectedVertices=g:(this.projectedVertices={},this.projectedVertices.v1=new mea3D.Vector3(0,0,0),this.projectedVertices.v2=
new mea3D.Vector3(0,0,0),this.projectedVertices.v3=new mea3D.Vector3(0,0,0),this.projectedVertices.v4=new mea3D.Vector3(0,0,0));this.material=h;this.calculateNormalsAndCenters();this.calculateEdges()};
mea3D.Polygon.prototype={toString:function(){return this.v4?"(v1:"+this.v1.pos+", v2:"+this.v2.pos+", v3:"+this.v3.pos+", v4:"+this.v4.pos+")":"(v1:"+this.v1.pos+", v2:"+this.v2.pos+", v3:"+this.v3.pos+")"},calculateNormalsAndCenters:function(){this.center=mea3D.Math.getFaceCenter(this.v1.pos,this.v2.pos,this.v3.pos,this.v4?this.v4.pos:null);this.normal=mea3D.Math.getFaceNormal(this.v1.pos,this.v2.pos,this.v3.pos,this.v4?this.v4.pos:null);this.transformedCenter=mea3D.Math.getFaceCenter(this.transformedVertices.v1,
this.transformedVertices.v2,this.transformedVertices.v3,this.transformedVertices.v4);this.transformedNormal=mea3D.Math.getFaceNormal(this.transformedVertices.v1,this.transformedVertices.v2,this.transformedVertices.v3,this.transformedVertices.v4)},calculateEdges:function(){this.edge1=this.v2.pos.subt(this.v1.pos);this.edge2=this.v3.pos.subt(this.v1.pos);this.dot_edge12=this.edge1.dot(this.edge2);this.dot_edge11=this.edge1.dot(this.edge1);this.dot_edge22=this.edge2.dot(this.edge2);this.minusCenterDotNormal=
-this.center.dot(this.normal);this.insidePolygonFormulaDenominator=this.dot_edge12*this.dot_edge12-this.dot_edge11*this.dot_edge22}};mea3D.Material=function(a,b,c,d){this.ambientColor=c?c:new mea3D.ColorRGBA(0,0,0);this.emitColor=d?d:new mea3D.ColorRGBA(0,0,0);this.reflectivity="undefined"==typeof a?0:a;this.enableEmitColor=this.enableAmbientColor=!0;if(b)this.texture=b};mea3D.Material.createFromTemplate=function(a,b){var c=null;b&&a.texture&&(c=b[a.texture-1]);c=new mea3D.Material(a.reflectivity,c);c.setColorValues(a.ambientColor,a.emitColor,a.diffuseColor,a.specularColor);return c};
mea3D.Material.prototype={setColorValues:function(a,b){if(a)this.ambientColor=mea3D.ColorRGBA.createFromValues(a);if(b)this.emitColor=mea3D.ColorRGBA.createFromValues(b)}};mea3D.Texture=function(a){this.image=null;a&&this.loadFromFile(a)};mea3D.Texture.prototype={loadFromFile:function(a){this.image=new Image;this.image.src=a}};mea3D.LightType={NONE:0,AMBIENT:1,SPOT:2,POINT:3,DIRECTIONAL:4};mea3D.Light=function(a,b,c,d,e,f,g){this.type=a;this.color=b?b:new mea3D.ColorRGBA(0,1,0);this.position=c;this.direction=d?d.norm():null;this.range=e;this.enabled="undefined"==typeof g?!0:g;if(e)this.rangeSquared=e*e;this.attenuation=f};
mea3D.Light.prototype={setEnabled:function(a){this.enabled=a},getEnabled:function(){return this.enabled},calculateAttenuationFactor:function(a){if(this.attenuation){var b=0;this.attenuation.att0&&(b+=this.attenuation.att0);this.attenuation.att1&&(b+=a*this.attenuation.att1);this.attenuation.att2&&(b+=a*a*this.attenuation.att2);return b?1/b:0}return 0},calculateColor:function(a,b,c){var d=new mea3D.ColorRGBA(0,0,0);switch(this.type){case mea3D.LightType.AMBIENT:return null;case mea3D.LightType.SPOT:return null;
case mea3D.LightType.DIRECTIONAL:return c=this.direction.dot(c),0>c&&(c=0),1<c&&(c=1),d.r=a.ambientColor.r*c*this.color.r,d.g=a.ambientColor.g*c*this.color.g,d.b=a.ambientColor.b*c*this.color.b,d;case mea3D.LightType.POINT:var e=b.subt(this.position),b=e.mag2();if(this.rangeSquared&&b>this.rangeSquared)return d;c=e.norm().dot(c);0>c&&(c=0);1<c&&(c=1);c*=this.calculateAttenuationFactor(Math.sqrt(b));d.r=a.ambientColor.r*c*this.color.r;d.g=a.ambientColor.g*c*this.color.g;d.b=a.ambientColor.b*c*this.color.b;
return d}}};mea3D.BoundingShapeType={NONE:0,BOX:1,SPHERE:2};mea3D.BoundingShape=function(a){if(a&&(this.params=a,this.type=a.type,this.ownerMesh=a.ownerMesh,this.position=a.position,this.finalPosition=a.finalPosition,this.type==mea3D.BoundingShapeType.SPHERE))this.radius=a.radius,this.radiusSquared=this.radius*this.radius};mea3D.BoundingShape.prototype={toString:function(){return this.type==mea3D.BoundingShapeType.SPHERE?this.position.toString()+" - r:"+this.radius:this.position.toString()},copy:function(){return new mea3D.BoundingShape(this.params)}};mea3D.MeshType={MESH_NONE:0,MESH_POLYGON:1,MESH_SURFACE:2,MESH_TEXT:3};mea3D.Mesh=function(a,b){this.parent=a;b||(b={});this.name=b.name;this.material=b.meshMaterial;this.transformation=b.transformation?b.transformation:new mea3D.Transformation;this.finalTransformation=new mea3D.Transformation;this.numVertices=this.numFaces=0};
mea3D.Mesh.createFromTemplate=function(a,b,c,d,e){var f=null;c.materialIndex&&d&&c.materialIndex-1<d.length&&(f=d[c.materialIndex-1]);a=new mea3D.Mesh(a,{meshMaterial:f,transformation:e,name:b});"undefined"==typeof c.type||c.type==mea3D.MeshType.MESH_POLYGON||"polygon"==c.type?a.buildPolyMesh(c.vertices,c.faceIndices,c.faceMaterialIndices,d):c.type==mea3D.MeshType.MESH_SURFACE||"surface"==c.type?a.buildSurfaceMesh(c.radius):(c.type==mea3D.MeshType.MESH_TEXT||"text"==c.type)&&a.buildTextMesh(c.text);
return a};
mea3D.Mesh.prototype={buildPolyMesh:function(a,b,c,d){this.type=mea3D.MeshType.MESH_POLYGON;this.initPolyMesh(a,b,c,d)},buildSurfaceMesh:function(a){this.type=mea3D.MeshType.MESH_SURFACE;this.radius=a},buildTextMesh:function(a){this.type=mea3D.MeshType.MESH_TEXT;this.text=a},initPolyMesh:function(a,b,c,d){if(a&&b){this.vertices=Array(a.length/3);for(var e=0;e<a.length;e+=3)this.vertices[e/3]=new mea3D.Vector3(a[e],a[e+1],a[e+2]);this.numVertices=this.vertices.length;this.worldTransformedVertices=Array(this.numVertices);
this.projectedVertices=Array(this.numVertices);for(e=0;e<this.numVertices;e++)this.projectedVertices[e]=new mea3D.Vector3(0,0,0),this.worldTransformedVertices[e]=new mea3D.Vector3(0,0,0);this.worldTransformVertices();if(c){this.faceMaterials=Array(c.length);for(e=0;e<c.length;e++)this.faceMaterials[e]=d[c[e]]}this.numFaces=0;this.faceIndices=[];this.polygons=[];for(e=0;e<b.length;++e){var f=b[e].length;if(!(3!=f&&4!=f)){var a=b[e][0],d=b[e][1],g=b[e][2],h=new mea3D.Vertex(this.vertices[a].x,this.vertices[a].y,
this.vertices[a].z),i=new mea3D.Vertex(this.vertices[d].x,this.vertices[d].y,this.vertices[d].z),k=new mea3D.Vertex(this.vertices[g].x,this.vertices[g].y,this.vertices[g].z),j=null;(j=c?this.faceMaterials[c[e]]:this.material)||(j=new mea3D.Material(0,null,new mea3D.ColorRGBA(0.6,0.6,0.6)));if(4==f){f=b[e][3];this.faceIndices.push([a,d,g,f]);var l=new mea3D.Vertex(this.vertices[f].x,this.vertices[f].y,this.vertices[f].z);this.polygons.push(new mea3D.Polygon(mea3D.RenderableType.POLYGON,h,i,k,l,{v1:this.worldTransformedVertices[a],
v2:this.worldTransformedVertices[d],v3:this.worldTransformedVertices[g],v4:this.worldTransformedVertices[f]},{v1:this.projectedVertices[a],v2:this.projectedVertices[d],v3:this.projectedVertices[g],v4:this.projectedVertices[f]},j))}else this.faceIndices.push([a,d,g]),this.polygons.push(new mea3D.Polygon(mea3D.RenderableType.POLYGON,h,i,k,null,{v1:this.worldTransformedVertices[a],v2:this.worldTransformedVertices[d],v3:this.worldTransformedVertices[g],v4:null},{v1:this.projectedVertices[a],v2:this.projectedVertices[d],
v3:this.projectedVertices[g],v4:null},j))}}this.numFaces=this.faceIndices.length;this.updateTransformation()}},updateTransformation:function(){this.transformation.update();this.finalTransformation.matrix=mea3D.Math.mult4(this.transformation.matrix,this.parent.transformation.matrix);this.finalTransformation.position=this.transformation.position.add(this.parent.transformation.position);this.finalTransformation.scaling.x=this.transformation.scaling.x*this.parent.transformation.scaling.x;this.finalTransformation.scaling.y=
this.transformation.scaling.y*this.parent.transformation.scaling.y;this.finalTransformation.scaling.z=this.transformation.scaling.z*this.parent.transformation.scaling.z;this.updateCentersAndNormals()},worldTransformVertices:function(){for(var a,b=0;b<this.numVertices;++b)a=mea3D.Math.transformPoint(this.vertices[b],this.finalTransformation.matrix),this.worldTransformedVertices[b].x=a.x,this.worldTransformedVertices[b].y=a.y,this.worldTransformedVertices[b].z=a.z},updateCentersAndNormals:function(){this.worldTransformVertices();
for(var a=0;a<this.numFaces;++a)this.polygons[a].calculateNormalsAndCenters()},projectVertices:function(a,b,c){for(var d,e=0;e<this.numVertices;e++)d=mea3D.Math.transformPoint(this.worldTransformedVertices[e],a),d.x/=d.z,d.y/=d.z,d.x=d.x*b/(2*d.w)+b/2,d.y=-(d.y*c/(2*d.w))+c/2,this.projectedVertices[e].x=d.x,this.projectedVertices[e].y=d.y,this.projectedVertices[e].z=d.z},calculateLighting:function(a,b){for(var c,d=0;d<this.numFaces;++d)c=this.polygons[d],c.computedColor=mea3D.Math.computeLighting(c.transformedCenter,
c.transformedNormal,c.material,a,b)},calculateBoundingShapeParameters:function(){if(this.type==mea3D.MeshType.MESH_SURFACE||"surface"==this.type)return mea3D.Logging.log("Bounding surface radius: "+this.radius),{radius:this.radius,position:new mea3D.Vector3(0,0,0)};if("undefined"==typeof this.type||this.type==mea3D.MeshType.MESH_POLYGON||"polygon"==this.type){var a;a=this.transformation.scaling.x*this.transformation.scaling.x*this.parent.transformation.scaling.x*this.parent.transformation.scaling.x;
for(var b=[],c=0;c<this.numFaces;++c){var d=this.faceIndices[c][3],e=this.vertices[this.faceIndices[c][1]],f=this.vertices[this.faceIndices[c][2]],d=d?this.vertices[d]:null;b.push(this.vertices[this.faceIndices[c][0]]);b.push(e);b.push(f);d&&b.push(d)}e=new mea3D.Vector3(0,0,0);if(b&&0<b.length){for(c=0;c<b.length;c++)e.x+=b[c].x,e.y+=b[c].y,e.z+=b[c].z;e.x/=b.length;e.y/=b.length;e.z/=b.length;for(c=f=0;c<b.length;c++)d=b[c].subt(e).mag2()*a,d>f&&(f=d);a=Math.sqrt(f)}else a=0;return{radius:a,position:e}}return{radius:0,
position:new mea3D.Vector3(0,0,0)}},calculateBoundingShape:function(){var a=this.calculateBoundingShapeParameters();if(a)this.boundingShape=new mea3D.BoundingShape({type:mea3D.BoundingShapeType.SPHERE,position:a.position,radius:a.radius,finalPosition:this.finalTransformation.position.add(a.position),ownerMesh:this}),mea3D.Logging.log("Bounding shape calculated : "+this.boundingShape)},moveTo:function(a,b,c){this.transformation.moveTo(a,b,c)},move:function(a,b,c){this.transformation.move(a,b,c)},rotate:function(a,
b,c){this.transformation.rotate(a,b,c)},scale:function(a){this.transformation.scale(a)},scale3:function(a,b,c){this.transformation.scale3(a,b,c)}};mea3D.Model3D=function(a,b,c){this.name=a;this.transformation=c?c:new mea3D.Transformation;this.numVertices=this.numFaces=0;this.meshNames={};this.textures=null;if(b&&b.textures){this.textures=Array(b.textures.length);for(a=0;a<b.textures.length;a++)this.textures[a]=new mea3D.Texture(b.textures[a])}this.materials=null;if(b&&b.materials){this.materials=Array(b.materials.length);for(a=0;a<b.materials.length;a++)this.materials[a]=mea3D.Material.createFromTemplate(b.materials[a],this.textures)}b&&this.loadFromTemplate(b);
this.updateTransformation()};
mea3D.Model3D.prototype={loadFromTemplate:function(a){this.meshList=null;if(a&&a.meshList){this.meshList=Array(a.meshList.length);for(var b=0;b<a.meshList.length;b++)this.meshList[b]=mea3D.Mesh.createFromTemplate(this,a.meshList[b].name,a.meshList[b],this.materials),this.meshNames[a.meshList[b].name]=this.meshList[b],this.numFaces+=this.meshList[b].numFaces,this.numVertices+=this.meshList[b].numVertices}},getMeshByName:function(a){return this.meshNames[a]},updateTransformation:function(){this.transformation.update();this.updateMeshes()},
updateMeshes:function(){if(this.meshList)for(var a=0;a<this.meshList.length;a++)this.meshList[a].updateTransformation()},addMesh:function(a,b){if(!this.meshList)this.meshList=[];if(b)a.transformation=b;a.parent=this;if(!a.material)a.material=this.materials&&0<this.materials.length?this.materials[0]:new mea3D.Material;a.updateTransformation();this.meshList.push(a);a.name&&(this.meshNames[a.name]=a)},calculateBoundingShapeParameters:function(){for(var a=[],b=0;b<this.meshList.length;b++)this.meshList[b].calculateBoundingShape(),
this.meshList[b].boundingShape&&a.push({radius:this.meshList[b].boundingShape.radius,position:this.meshList[b].transformation.position.add(this.meshList[b].boundingShape.position)});return mea3D.Math.getMinimumBoundingSphere(a)},calculateBoundingShape:function(){var a=this.calculateBoundingShapeParameters();this.boundingShape=new mea3D.BoundingShape({type:mea3D.BoundingShapeType.SPHERE,position:a.position,finalPosition:this.transformation.position.add(a.position),radius:a.radius,ownerMesh:this})},
moveTo:function(a,b,c){this.transformation.moveTo(a,b,c)},move:function(a,b,c){this.transformation.move(a,b,c)},rotate:function(a,b,c){this.transformation.rotate(a,b,c)},scale:function(a){this.transformation.scale(a)},scale3:function(a,b,c){this.transformation.scale3(a,b,c)}};mea3D.KeyCodes={KEYCODE_A:65,KEYCODE_B:66,KEYCODE_C:67,KEYCODE_D:68,KEYCODE_E:69,KEYCODE_F:70,KEYCODE_G:71,KEYCODE_H:72,KEYCODE_I:73,KEYCODE_J:74,KEYCODE_K:75,KEYCODE_L:76,KEYCODE_M:77,KEYCODE_N:78,KEYCODE_O:79,KEYCODE_P:80,KEYCODE_Q:81,KEYCODE_R:82,KEYCODE_S:83,KEYCODE_T:84,KEYCODE_U:85,KEYCODE_V:86,KEYCODE_W:87,KEYCODE_X:88,KEYCODE_Y:89,KEYCODE_Z:90,KEYCODE_UP:38,KEYCODE_DOWN:40,KEYCODE_LEFT:37,KEYCODE_RIGHT:39,KEYCODE_0:48,KEYCODE_1:49,KEYCODE_2:50,KEYCODE_3:51,KEYCODE_4:52,KEYCODE_5:53,KEYCODE_6:54,
KEYCODE_7:55,KEYCODE_8:56,KEYCODE_9:57,KEYCODE_SPACE:32,KEYCODE_PERIOD:190};mea3D.Scene=function(){this.models=[];this.modelsHash={};this.skyBox=null;this.lights=[];this.ambientColor=new mea3D.ColorRGBA(0,0,0);this.boundingShapes=[]};
mea3D.Scene.prototype={addModel:function(a){a&&(this.modelsHash[a.name]=a,this.models.push(a))},getModelByName:function(a){return this.modelsHash[a]},addLight:function(a){a&&this.lights.push(a)},addBoundingShape:function(a){this.boundingShapes.push(a)},getLights:function(){return this.lights},hitTestBoundingShape:function(a,b){for(var c=-1,d=null,e,f=0;f<this.boundingShapes.length;++f){e=this.boundingShapes[f];var g=mea3D.Math.distanceSquaredPointToLine(e.finalPosition,a,b);if(g<e.radiusSquared&&
(-1==c||g<c))c=g,d=e}return d},highlightMesh:function(a,b){if(a&&a.material)a.material.enableEmitColor=b},hitTestBoundingShapes:function(a,b,c,d){a=mea3D.Math.Util.getPixelDirectionVector(a.width,a.height,c,d,b.getFovHorizontal(),b.getFovVertical(),b.getEyeDir(),b.getUpVector(),b.getLeftVector()).norm();b=b.getEyePos();b.add(a.scale(1,1,1));return this.hitTestBoundingShape(b,a)},prevSelectedShape:null,getMouseSelection:function(a,b,c,d){a=this.hitTestBoundingShapes(a,b,c,d);if(this.prevSelectedShape!=
a){this.prevSelectedShape&&this.highlightMesh(this.prevSelectedShape.ownerMesh,!1);if(this.prevSelectedShape&&this.prevSelectedShape.onMouseOut)this.prevSelectedShape.onMouseOut(this.prevSelectedShape);if(a&&(this.highlightMesh(a.ownerMesh,!0),a.onMouseOver))a.onMouseOver(a);this.prevSelectedShape=a}return a}};mea3D.Canvas2DRenderer=function(a,b,c,d){this.canvas=a;this.viewport=b;this.options=c;this.sceneProjection=this.context=null;this.renderStats=d;this.currentStrokeColor=new mea3D.ColorRGBA;this.currentFillColor=new mea3D.ColorRGBA};
mea3D.Canvas2DRenderer.prototype={init:function(){if(!this.canvas.getContext)return!1;this.context=this.canvas.getContext("2d");if(!this.context)throw"Error creating 2D context";this.context.lineWidth=2;this.sceneProjection=new mea3D.SceneProjection(this.options,this.viewport,this.renderStats)},setStrokeColor:function(a){if(!this.currentStrokeColor.equals(a))this.context.strokeStyle=a.toString(),this.currentStrokeColor=a},setFillColor:function(a){if(!this.currentFillColor.equals(a))this.context.fillStyle=
a.toString(),this.currentFillColor=a},drawRect:function(a,b,c,d,e){e&&this.setFillColor(e);this.context.fillRect(a,b,c,d)},drawLine2D:function(a,b,c,d,e,f){e&&this.setStrokeColor(e);if(f)this.context.lineWidth=f;this.context.beginPath();this.context.moveTo(a,b);this.context.lineTo(c,d);this.context.stroke();this.context.closePath()},drawLine:function(a,b,c,d){function e(a){0>a.z&&(a.x*=a.z,a.y*=a.z)}var f=this.sceneProjection.project(a),g=this.sceneProjection.project(b);if(f&&g){var h=f.copy(),i=
g.copy();e(h,a);e(i,b);this.drawLine2D(f.x,f.y,g.x,g.y,c,d);this.drawRect(f.x-3,f.y-3,6,6,new mea3D.ColorRGBA(1,0,0));this.drawRect(g.x-3,g.y-3,6,6,new mea3D.ColorRGBA(0,1,1))}},drawPoint2D:function(a,b,c){this.drawRect(a-2,b-2,4,4,c)},drawPoint:function(a,b){var c=this.sceneProjection.project(a);c&&this.drawPoint2D(c.x,c.y,b)},drawPolygon2D:function(a,b,c,d,e){e&&this.setFillColor(e);this.context.lineWidth=2;this.context.beginPath();this.context.moveTo(a.x,a.y);this.context.lineTo(b.x,b.y);this.context.lineTo(c.x,
c.y);d&&this.context.lineTo(d.x,d.y);this.context.fill();this.context.closePath()},renderText2D:function(a,b,c,d){d&&this.setFillColor(d);if(c)this.context.font=c+"pt Arial";this.context.fillText(a,b.x,b.y)},renderText:function(a,b,c,d){d&&this.setFillColor(d);if(c)this.context.font=c+"pt Arial";b=this.sceneProjection.project(b);this.context.fillText(a,b.x,b.y)},renderCircle2D:function(a,b,c){c&&this.setFillColor(c);this.context.beginPath();this.context.arc(a.x,a.y,b,0,2*Math.PI,!0);this.context.closePath();
this.context.stroke()},clear:function(){this.drawRect(0,0,this.viewport.width,this.viewport.height,this.options.clearColor)},beginDraw:function(){this.sceneProjection.clear()},drawScene:function(a){this.sceneProjection.drawScene(a)},endDraw:function(){},beginRender:function(){this.clear()},render:function(){for(var a=this.sceneProjection.renderBuffer,b=a.length,c=b-1;0<=c;c--){var d=a[c];switch(d.type){case mea3D.RenderableType.POLYGON:this.renderPolygon(d.projectedVertices.v1,d.projectedVertices.v2,
d.projectedVertices.v3,d.projectedVertices.v4,d.computedColor,d.material&&d.material.texture?d.material.texture:null);break;case mea3D.RenderableType.SURFACE:this.renderCircle2D(d.position,d.radius,d.color);break;case mea3D.RenderableType.TEXT:this.renderText2D(d.text,d.position,d.fontSize,d.color)}}this.renderStats.polygonsRendered=b;this.renderStats.framesRendered++},endRender:function(){},renderPolygon:function(a,b,c,d,e,f){switch(this.options.renderMode){case mea3D.RenderModes.RENDER_FACES:this.drawPolygon2D(a,
b,c,d,e,f&&f.image?f.image:null);break;case mea3D.RenderModes.RENDER_WIREFRAMES:d?(this.drawLine2D(a.x,a.y,b.x,b.y,e),this.drawLine2D(b.x,b.y,c.x,c.y),this.drawLine2D(c.x,c.y,d.x,d.y),this.drawLine2D(d.x,d.y,a.x,a.y)):(this.drawLine2D(a.x,a.y,b.x,b.y,e),this.drawLine2D(a.x,a.y,c.x,c.y),this.drawLine2D(b.x,b.y,c.x,c.y));break;case mea3D.RenderModes.RENDER_POINTS:this.drawPoint2D(a.x,a.y,e),this.drawPoint2D(b.x,b.y),this.drawPoint2D(c.x,c.y),d&&this.drawPoint2D(d.x,d.y)}},setTransformMatrix:function(a){this.sceneProjection.setTransformMatrix(a)}};
mea3D.SceneProjection=function(a,b,c){this.renderBuffer=[];this.renderStats=c;this.viewport=b;this.options=a};
mea3D.SceneProjection.prototype={clear:function(){this.renderBuffer=[];this.renderStats.verticesRendered=0},drawSurfaceMesh:function(a){var b=mea3D.Math.transformPoint(a.finalTransformation.position,this.matrixTransform);b.x/=b.z;b.y/=b.z;b.x=b.x*this.viewport.width/2+this.viewport.width/2;b.y=-(b.y*this.viewport.height/2)+this.viewport.height/2;a=a.finalTransformation.position.add(new mea3D.Vector3(0,a.radius,0));a=mea3D.Math.transformPoint(a,this.matrixTransform);a.x/=a.z;a.y/=a.z;a.x=a.x*this.viewport.width/
2+this.viewport.width/2;a.y=-(a.y*this.viewport.height/2)+this.viewport.height/2;a=(new mea3D.Vector2(b.x-a.x,b.y-a.y)).mag();this.renderBuffer.push({position:b,radius:a,color:new mea3D.ColorRGBA(1,1,0),type:mea3D.RenderableType.SURFACE,projectedCenter:b})},drawTextMesh:function(a){a.fontSize=1;var b=mea3D.Math.transformPoint(a.finalTransformation.position,this.matrixTransform);b.x/=b.z;b.y/=b.z;b.x=b.x*this.viewport.width/2+this.viewport.width/2;b.y=-(b.y*this.viewport.height/2)+this.viewport.height/
2;var c=a.finalTransformation.position.add(new mea3D.Vector3(0,a.fontSize*a.finalTransformation.scaling.x,0)),c=mea3D.Math.transformPoint(c,this.matrixTransform);c.x/=c.z;c.y/=c.z;c.x=c.x*this.viewport.width/2+this.viewport.width/2;c.y=-(c.y*this.viewport.height/2)+this.viewport.height/2;c=new mea3D.Vector2(b.x-c.x,b.y-c.y);c=c.mag();this.renderBuffer.push({position:b,text:a.text,fontSize:c,color:a.material.ambientColor,type:mea3D.RenderableType.TEXT,projectedCenter:b})},drawMesh:function(a,b,c){switch(a.type){case mea3D.MeshType.MESH_POLYGON:this.drawPolygonMesh(a,
b,c);break;case mea3D.MeshType.MESH_SURFACE:this.drawSurfaceMesh(a,b,c);break;case mea3D.MeshType.MESH_TEXT:this.drawTextMesh(a,b,c)}},setTransformMatrix:function(a){this.matrixTransform=a},drawPolygonMesh:function(a,b,c){a.updateCentersAndNormals();a.projectVertices(this.matrixTransform,this.viewport.width,this.viewport.height);this.renderStats.verticesRendered+=a.vertices.length;this.drawPolygonList(a.polygons,b,c)},drawPolygonList:function(a,b,c){for(var d=a.length,e=0;e<d;++e){var f=a[e],g=f.projectedVertices.v1,
h=f.projectedVertices.v2,i=f.projectedVertices.v3,k=f.projectedVertices.v4;if(!(0>g.z||0>h.z||0>i.z||4==f.vertexCount&&0>k.z)){if(this.options.backfaceCulling&&(h=g.subt(h),g=g.subt(i),i=new mea3D.Vector3(h.x,h.y,0),g=new mea3D.Vector3(g.x,g.y,0),0>i.cross(g).z))continue;f.projectedCenter=mea3D.Math.getFaceCenter(f.projectedVertices.v1,f.projectedVertices.v2,f.projectedVertices.v3,f.projectedVertices.v4);if(f.material)f.computedColor=mea3D.Math.Util.computeLighting(f.transformedCenter,f.transformedNormal,
f.material,b,c);this.renderBuffer.push(f)}}},drawModel:function(a,b,c){for(var d=0;d<a.meshList.length;d++)this.drawMesh(a.meshList[d],b,c)},sortFunction:function(a,b){return a.projectedCenter.z-b.projectedCenter.z},drawScene:function(a){for(var b=0;b<a.models.length;b++)this.drawModel(a.models[b],a.lights,a.ambientColor);this.renderBuffer.sort(this.sortFunction);a.skyBox&&this.drawModel(a.skyBox,a.lights,a.ambientColor)},project:function(a){a=mea3D.Math.transformPoint(a,this.matrixTransform);a.x/=
a.z;a.y/=a.z;a.x=a.x*this.viewport.width/2+this.viewport.width/2;a.y=-(a.y*this.viewport.height/2)+this.viewport.height/2;return a}};mea3D.RenderModes={RENDER_NONE:0,RENDER_POINTS:1,RENDER_WIREFRAMES:2,RENDER_FACES:3};mea3D.RenderStats=function(){this.framesRendered=this.polygonsRendered=this.verticesRendered=0};
mea3D.Renderer=function(a,b){if(!a)return!1;this.container=a;var c={width:800,height:600,backfaceCulling:!0,clearColor:new mea3D.ColorRGBA(0,0,0),renderMode:mea3D.RenderModes.RENDER_FACES,enableMouseNavigation:!0,cameraPosition:new mea3D.Vector3(0,0,0),cameraDirection:new mea3D.Vector3(0,0,1),cameraUpVector:new mea3D.Vector3(0,1,0),fovHorizontal:Math.PI/3,aspectRatio:this.width/this.height,fovVertical:Math.PI/this.aspectRatio};this.options=mea3D.getOptions(b,c);this.options.aspectRatio=this.options.width/
this.options.height;if(!this.options.fovVertical)this.options.fovVertical=this.options.fovHorizontal/this.options.aspectRatio;this.viewport=new mea3D.ViewPort(0,0,this.options.width,this.options.height,0.1,1E5);this.camera=new mea3D.Camera(this.options.cameraPosition.copy(),this.options.cameraDirection.norm(),this.options.cameraUpVector,this.options.fovHorizontal,this.options.fovVertical);this.container.style.width=this.viewport.width+"px";this.container.style.height=this.viewport.height+"px";this.renderStats=
new mea3D.RenderStats;this.initialized=!1;this.init();this.reset()};
mea3D.Renderer.prototype={init:function(){this.canvas=mea3D.Utils.getCanvasElement(this.container);if(!this.canvas)this.canvas=mea3D.Utils.createCanvas(this.container,this.viewport.width,this.viewport.height);this.context=new mea3D.Canvas2DRenderer(this.canvas,this.viewport,this.options,this.renderStats);this.context.init();return this.initialized=!0},isInitialized:function(){return this.initialized},reset:function(){if(!this.isInitialized())return!1;this.worldTransform=new mea3D.Matrix4;this.updateProjectionMatrix();
this.updateTransformMatrix()},updateProjectionMatrix:function(){this.projectionTransform=mea3D.Math.getProjectionMatrix4(this.viewport.zNear,this.viewport.zFar,this.camera.getFovHorizontal(),this.camera.getFovVertical())},updateTransformMatrix:function(){this.camera.update();this.matrixWorldView=mea3D.Math.mult4(this.worldTransform,this.camera.getViewTransform());this.matrixTransform=mea3D.Math.mult4(this.matrixWorldView,this.projectionTransform);this.screenProjectionMatrix=mea3D.Math.getScreenProjectionMatrix4(0,
0,this.viewport.width,this.viewport.height,this.viewport.zNear,this.viewport.zFar);this.context.setTransformMatrix(this.matrixTransform)},setStrokeColor:function(a){this.context.setStrokeColor(a)},setFillColor:function(a){this.context.setFillColor(a)},drawRect:function(a,b,c,d,e){this.context.drawRect(a,b,c,d,e)},drawLine2D:function(a,b,c,d,e,f){this.context.drawLine2D(a,b,c,d,e,f)},drawLine:function(a,b,c,d){this.context.drawLine(a,b,c,d)},drawPoint2D:function(a,b,c){this.context.drawPoint2D(a,b,
c)},drawPoint:function(a,b){this.context.drawPoint(a,b)},drawPolygon2D:function(a,b,c,d,e,f){this.context.drawPolygon2D(a,b,c,d,e,f)},renderText2D:function(a,b,c,d){this.context.renderText2D(a,b,c,d)},renderText:function(a,b,c,d){this.context.renderText(a,b,c,d)},renderCircle2D:function(a,b,c){this.context.renderCircle2D(a,b,c)},clear:function(){this.context.clear()},update:function(a){this.clear();this.context.beginDraw();this.context.drawScene(a);this.context.endDraw();this.context.beginRender();
this.context.render();this.context.endRender()},screenToViewportCoords:function(a,b){var c=this.viewport.width/2,d=this.viewport.height/2;return new mea3D.Vector2((a-c)/c,(b-d)/d)},getCamera:function(){return this.camera},getCanvas:function(){return this.canvas}};mea3D.FPSCalculator=function(){this.startTime=this.currentTime=new Date;this.numFrames=this.fps=this.lastFPSCalculationTime=0};mea3D.FPSCalculator.prototype={update:function(){this.currentTime=new Date;this.numFrames++;var a=(this.currentTime-this.startTime)/1E3;if(100<this.currentTime-this.lastFPSCalculationTime)this.fps=this.numFrames/a,this.lastFPSCalculationTime=this.currentTime;if(2<a)this.numFrames=0,this.startTime=this.currentTime}};window.mea3D=mea3D;mea3D.ColorRGBA=mea3D.ColorRGBA;mea3D.Vector3=mea3D.Vector3;mea3D.Light=mea3D.Light;mea3D.LightType=mea3D.LightType;mea3D.Light.prototype.setEnabled=mea3D.Light.prototype.setEnabled;mea3D.Light.prototype.getEnabled=mea3D.Light.prototype.getEnabled;mea3D.Material=mea3D.Material;mea3D.Mesh=mea3D.Mesh;mea3D.Mesh.createFromTemplate=mea3D.Mesh.createFromTemplate;mea3D.Transformation=mea3D.Transformation;mea3D.Model3D=mea3D.Model3D;mea3D.Model3D.prototype.addMesh=mea3D.Model3D.prototype.addMesh;
mea3D.Model3D.prototype.updateTransformation=mea3D.Model3D.prototype.updateTransformation;mea3D.Camera=mea3D.Camera;mea3D.Camera.prototype.getEyePos=mea3D.Camera.prototype.getEyePos;mea3D.Camera.prototype.moveTo=mea3D.Camera.prototype.moveTo;mea3D.Camera.prototype.getEyeDir=mea3D.Camera.prototype.getEyeDir;mea3D.Camera.prototype.setEyeDir=mea3D.Camera.prototype.setEyeDir;mea3D.Camera.prototype.getFovHorizontal=mea3D.Camera.prototype.getFovHorizontal;mea3D.Camera.prototype.getFovVertical=mea3D.Camera.prototype.getFovVertical;
mea3D.Camera.prototype.getUpVector=mea3D.Camera.prototype.getUpVector;mea3D.Camera.prototype.moveByMouseDelta=mea3D.Camera.prototype.moveByMouseDelta;mea3D.Camera.prototype.moveForwardBackward=mea3D.Camera.prototype.moveForwardBackward;mea3D.Camera.prototype.moveLeftRight=mea3D.Camera.prototype.moveLeftRight;mea3D.Camera.prototype.rotateYaw=mea3D.Camera.prototype.rotateYaw;mea3D.Camera.prototype.rotatePitch=mea3D.Camera.prototype.rotatePitch;mea3D.Renderer=mea3D.Renderer;
mea3D.Renderer.prototype.isInitialized=mea3D.Renderer.prototype.isInitialized;mea3D.Renderer.prototype.getCamera=mea3D.Renderer.prototype.getCamera;mea3D.Renderer.prototype.getCanvas=mea3D.Renderer.prototype.getCanvas;mea3D.Renderer.prototype.update=mea3D.Renderer.prototype.update;mea3D.Scene=mea3D.Scene;mea3D.Scene.prototype.addModel=mea3D.Scene.prototype.addModel;mea3D.Scene.prototype.addLight=mea3D.Scene.prototype.addLight;mea3D.Scene.prototype.getLights=mea3D.Scene.prototype.getLights;
mea3D.Utils=mea3D.Utils;mea3D.Utils.getPageOffsetTop=mea3D.Utils.getPageOffsetTop;mea3D.Utils.getPageOffsetLeft=mea3D.Utils.getPageOffsetLeft;mea3D.Utils.getXYValues=mea3D.Utils.getXYValues;mea3D.Utils.getElementsByTagName=mea3D.Utils.getElementsByTagName;mea3D.Utils.getCanvasElement=mea3D.Utils.getCanvasElement;mea3D.Utils.createCanvas=mea3D.Utils.createCanvas;})();
